name = "DungBase"
uuid = "bd6f3a87-2f53-57d0-9c4e-5625ef189a5e"
authors = ["yakir12 <12.yakir@gmail.com>"]
version = "0.2.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
IntervalSets = "8197267c-284f-5f27-9208-e0e47529a953"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
IntervalSets = "0.3.2"
StaticArrays = "0.11.0"

[targets]
test = ["Test"]
